### ISSUE TITLE
You need libattr headers for Shake to build.

### ISSUE THREAD

**Issue by antonio-petricca** [unbrice/shake#23]
OS: Linux Mint 18.03 64 bit (Ubuntu 16.04)
Dependencies: Installed **libattr1-dev**.

> cmake ..
> CMake Error at CMakeLists.txt:44 (message):
>   Cannot find help2man.  Please install it.
> 
> 
> CMake Warning (dev) at CMakeLists.txt:26 (get_target_property):
>   Policy CMP0026 is not set: Disallow use of the LOCATION target property.
>   Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   The LOCATION property should not be read from target "shake".  Use the
>   target name directly with add_custom_command, or use the generator
>   expression $<TARGET_FILE>, as appropriate.
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:50 (add_help2man_manpage)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at CMakeLists.txt:26 (get_target_property):
>   Policy CMP0026 is not set: Disallow use of the LOCATION target property.
>   Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   The LOCATION property should not be read from target "unattr".  Use the
>   target name directly with add_custom_command, or use the generator
>   expression $<TARGET_FILE>, as appropriate.
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:51 (add_help2man_manpage)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Error at CMakeLists.txt:87 (message):
>   You need libattr headers for Shake to build.  They might be in a package
>   named libattr1-dev or libattr-devel.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/antonio/projects/github/others/shake/build/CMakeFiles/CMakeOutput.log".
> See also "/home/antonio/projects/github/others/shake/build/CMakeFiles/CMakeError.log".
>

**Comment by antonio-petricca** [comment]
Issue solved.

**Comment by mmuncan1980** [comment]
no, not solved. same here, newest kali. :-/
